services:
  postgres:
    command:
      - postgres
      - -c
      - wal_level=logical

    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/:/docker-entrypoint-initdb.d

  producer:
    build: ./services/producer
    container_name: producer
    restart: on-failure
    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      kafka_broker:
        condition: service_started
      kafka_controller:
        condition: service_started

  consumer:
    build: ./services/consumer
    container_name: consumer
    restart: on-failure

    depends_on:
      postgres:
        condition: service_started
      kafka_broker:
        condition: service_started
      kafka_controller:
        condition: service_started

  debezium:
    image: debezium/connect:2.7.3.Final
    container_name: debezium

    ports:
      - "8083:8083"

    environment:
      BOOTSTRAP_SERVERS: kafka_broker:9092

      GROUP_ID: 1

      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

    depends_on:
      - kafka_broker
      - kafka_controller

  kafka_broker:
    image: apache/kafka:4.0.0
    container_name: kafka_broker

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker

      # Listen on all interfaces inside container
      KAFKA_LISTENERS: PLAINTEXT://:9092

      # Clients inside docker network use this hostname
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Shared cluster id
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # Controller quorum
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # FIX: use VOTERS, not VOTES
      KAFKA_CONTROLLER_QUORUM_VOTERS: 2@kafka_controller:9093

    depends_on:
      postgres:
        condition: service_healthy

  kafka_controller:
    image: apache/kafka:4.0.0
    container_name: kafka_controller

    ports:
      - "9093:9093"

    environment:
      KAFKA_NODE_ID: 2

      KAFKA_PROCESS_ROLES: controller

      # Listen on all interfaces
      KAFKA_LISTENERS: CONTROLLER://:9093

      # Shared cluster id
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # FIX: use VOTERS, not VOTES
      KAFKA_CONTROLLER_QUORUM_VOTERS: 2@kafka_controller:9093

      # FIX: removed KAFKA_ADVERTISED_LISTENERS
      # Controllers do not advertise client endpoints

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: